# Use postgres/example user/password credentials
version: '3.9'

services:


  test-db:
    image: postgres:16.3-alpine
#    container_name: db
#    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=test_database
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
volumes:
  pgdata:
